#spring:
#  profiles:
#    active:
#      - local
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/trillion
#    username: root
#    password: 0000
#  jpa:
#    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        hbm2ddl:
#          auto: update
#    database: mysql
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 200MB

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: test
    password: test1234!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
